r"""Batch-plumb and build the Halo 2 campaign for the Run Enhancer abilities.

The H2 counterpart of batch_build.py. For each mission it:
  1. inserts the ability plumbing into the SCENARIO TAG (h2_loosetag): an `ab_sprint`
     starting profile and `ab_camo0/1` object names + non-auto camo placements,
  2. writes this level's `ab_camo_spawn` / `ab_sprint_give` definitions over the
     global_scripts stubs,
  3. runs `tool.exe rebuild-scenario-scripts` -- REQUIRED after any .hsc edit, because
     build-cache-file compiles the scenario_hs_source_file TAG, not the source,
  4. runs `tool.exe build-cache-file`.

Because step 1 happens BEFORE the scripts compile, the names resolve and nothing is
borrowed -- so step 2's text is IDENTICAL on every mission. That is the whole point of
the tag-side approach; see h2_loosetag.py for the format and the history.

  python h2_batch.py --show                 # what is plumbed where
  python h2_batch.py --maps 05a --stage tag,script
  python h2_batch.py --maps 05a             # ...and rebuild scripts + build the cache
  python h2_batch.py                        # all 13 missions
"""
import argparse
import glob
import os
import re
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import h2_loosetag as L    # noqa: E402

H2EK = r'C:\Program Files (x86)\Steam\steamapps\common\H2EK'
TOOL = os.path.join(H2EK, 'tool.exe')
# Self-contained, single-language, and NOT asking for remastered.
#
# The EK's own script uses `compress|resource_sharing|multilingual_sounds|
# remastered_support`. All three extras are wrong here:
#   resource_sharing    offloads bitmaps and sounds into H2EK's shared .dat databases,
#                       which the MCC install does not have -- a 54 MB map against ~90 MB
#                       stock, with assets missing in game.
#   multilingual_sounds bundles every language set (1636 MB).
#   remastered_support  does NOTHING. Measured: building twice with identical flags
#                       differs in exactly the same 18 MB-chunks as building with the
#                       flag against without it (chunk 0 and a timestamped tail), so the
#                       whole difference is build nondeterminism. That figures -- the EK
#                       ships the classic 2004 tags, and the H2A art lives separately in
#                       groundhog/maps/shared.map keyed to the maps Bungie shipped. A
#                       rebuilt map has no remastered binding and plays classic-only,
#                       which is true of every map this toolkit builds.
CACHE_FLAGS = 'compress'
PLATFORM = 'win64'
MAPS_OUT = os.path.join(H2EK, 'h2_maps_win64_dx11')

# The halo.json "Missions / Halo 2" set, in its order. 00a_introduction and
# 01a_tutorial are deliberately absent: they are the cinematic intro and the armory
# walkthrough, not missions, and halo.json does not list them.
LEVELS = [
    ('01b', '01b_spacestation'), ('03a', '03a_oldmombasa'), ('03b', '03b_newmombasa'),
    ('04a', '04a_gasgiant'), ('04b', '04b_floodlab'), ('05a', '05a_deltaapproach'),
    ('05b', '05b_deltatowers'), ('06a', '06a_sentinelwalls'), ('06b', '06b_floodzone'),
    ('07a', '07a_highcharity'), ('08a', '08a_deltacliffs'), ('07b', '07b_forerunnership'),
    ('08b', '08b_deltacontrol'),
]
BY_SHORT = dict(LEVELS)

BEGIN = '; ===== Run Enhancer: ability plumbing (generated by h2_batch.py) ====='

# Identical on every level, because h2_loosetag put these names in the scenario tag.
# Camo does BOTH players: one pickup each, so co-op never contends over a single
# placement (the borrowed-name scheme could only ever serve player0).
STUB = BEGIN + '''
; global_scripts declares ab_camo_spawn / ab_sprint_give as stubs because it compiles
; into EVERY scenario, while object names and starting profiles are per scenario. The
; names below are inserted into this level's scenario tag before the scripts compile,
; so nothing is borrowed here -- see sprint_toolkit/h2_loosetag.py.
;
; Attached objects are parented and never run pickup collision, so the DETACH is what
; actually applies the powerup: all three steps are required.
(script static void ab_camo_spawn
\t(object_create ab_camo0)
\t(objects_attach (player0) "" ab_camo0 "")
\t(objects_detach (player0) ab_camo0)
\t(if (> (player_count) 1)
\t\t(begin
\t\t\t(object_create ab_camo1)
\t\t\t(objects_attach (player1) "" ab_camo1 "")
\t\t\t(objects_detach (player1) ab_camo1))))

(script static void ab_sprint_give
\t(unit_add_equipment (player0) ab_sprint false false)
\t(if (> (player_count) 1)
\t\t(unit_add_equipment (player1) ab_sprint false false)))
'''

# Lines that open a Run Enhancer block, current or legacy. Everything from the first
# one to EOF is replaced; verified that on 03a/03b/04a the block is the file's tail.
_MARKERS = (BEGIN, '; Run Enhancer', '(script static void ab_camo_spawn')


def scenario_path(level):
    return L._scenario(H2EK, level)


def mission_hsc(level):
    """This level's mission script. Most are <level>_mission.hsc, but several drop the
    level number -- 06a_sentinelwalls holds sentinelwalls_mission.hsc, 07b holds
    forerunnership_mission.hsc. Prefer the exact name, since 03a carries both its own
    and the shared earthcity_mission.hsc."""
    d = os.path.join(H2EK, 'data', 'scenarios', 'solo', level, 'scripts')
    exact = os.path.join(d, level + '_mission.hsc')
    if os.path.isfile(exact):
        return exact
    hits = sorted(glob.glob(os.path.join(d, '*_mission.hsc')))
    return hits[0] if hits else exact


_MARKER_RE = re.compile('^(?:%s)' % '|'.join(re.escape(m) for m in _MARKERS), re.M)


def _strip_existing(text):
    """Cut any previous ability block. Refuses if the tail holds anything other than
    our two script definitions, so an edit that landed mid-file is never truncated.

    Slices the text rather than splitting it into lines. str.splitlines() breaks on
    Unicode line boundaries, and 05a_deltaapproach_mission.hsc carries a raw 0x85 (NEL)
    byte inside the comment `;after cortana says "<0x85>such nice places."` -- splitting
    and rejoining there cut the comment in half, left `such nice places."` as a live
    expression, and broke the stock script 6500 lines above anything we wrote.
    """
    m = _MARKER_RE.search(text)
    if m is None:
        return text.rstrip() + '\n'
    tail = text[m.start():]
    defs = tail.count('(script ')
    if defs > 2 or 'ab_camo_spawn' not in tail or 'ab_sprint_give' not in tail:
        raise SystemExit('refusing to edit this script: the text after the first Run '
                         'Enhancer marker is not just the two ability scripts (found %d '
                         'script definitions). Fix it by hand.' % defs)
    return text[:m.start()].rstrip() + '\n'


def install_stub(level, verbose=True):
    path = mission_hsc(level)
    if not os.path.isfile(path):
        return False, 'no mission script'
    text = open(path, encoding='latin-1').read()
    bak = path + '.preability'
    body = _strip_existing(text)
    if not os.path.exists(bak):
        # Snapshot the PRISTINE text (block already removed), so re-running is stable.
        open(bak, 'w', encoding='latin-1').write(body)
        if verbose:
            print('    backed up -> %s' % os.path.basename(bak))
    new = body + '\n\n' + STUB
    if new == text:
        return True, 'already current'
    open(path, 'w', encoding='latin-1').write(new)
    return True, 'stub written'


def _backup(path, verbose):
    bak = path + '.preability'
    if not os.path.exists(bak):
        open(bak, 'wb').write(open(path, 'rb').read())
        if verbose:
            print('    backed up -> %s' % os.path.basename(bak))


def apply_tag(level, verbose=True):
    """The sprint profile goes in the SCENARIO; the camo pickups go in the equipment
    RESOURCE. They are different files because tool.exe stomps the scenario's placement
    blocks with the resource at build time -- see the RES_* note in h2_loosetag."""
    scn = scenario_path(level)
    _backup(scn, verbose)
    data = bytearray(open(scn, 'rb').read())
    profile = L.add_sprint_profile(data)
    if profile:
        open(scn, 'wb').write(bytes(data))

    res = L.resource_path(H2EK, level)
    if not os.path.isfile(res):
        return False, 'no scenario_equipment_resource'
    _backup(res, verbose)
    rdata = bytearray(open(res, 'rb').read())
    try:
        camo = L.add_camo_to_resource(rdata)
    except NotImplementedError as e:
        # 08b_deltacontrol ships no equipment at all, so there is no chunk to extend and
        # nothing to copy an element from. Report it and keep the sprint profile, rather
        # than aborting the whole batch over one level.
        return True, 'profile=%s  camo SKIPPED (%s)' % (profile, e)
    if camo:
        open(res, 'wb').write(bytes(rdata))

    if not profile and not camo:
        return True, 'tag already plumbed'
    return True, 'profile=%s  camo=%s' % (profile, ','.join(camo) or 'present')


def _tool(args, log):
    with open(log, 'w', encoding='latin-1', errors='replace') as f:
        p = subprocess.run([TOOL] + args, cwd=H2EK, stdout=f,
                           stderr=subprocess.STDOUT, text=True)
    out = open(log, encoding='latin-1', errors='replace').read()
    return p.returncode, out


def rebuild_scripts(level, logdir):
    rel = 'scenarios' + chr(92) + 'solo' + chr(92) + level + chr(92) + level
    rc, out = _tool(['rebuild-scenario-scripts', rel],
                    os.path.join(logdir, level + '.scripts.log'))
    bad = [l for l in out.splitlines() if 'error' in l.lower()]
    return (not bad), (bad[0][:90] if bad else 'scripts rebuilt')


def build_cache(level, logdir):
    rel = 'scenarios' + chr(92) + 'solo' + chr(92) + level + chr(92) + level
    built = os.path.join(MAPS_OUT, level + '.map')
    # A .map left over from an earlier run must NOT count as success -- os.path.exists
    # alone reported a clean build while the scripts were in fact failing to compile.
    was = os.path.getmtime(built) if os.path.exists(built) else 0
    rc, out = _tool(['-batch', 'build-cache-file', rel, PLATFORM, CACHE_FLAGS],
                    os.path.join(logdir, level + '.build.log'))
    fresh = os.path.exists(built) and os.path.getmtime(built) > was
    if 'successfully built' in out.lower() and fresh:
        return True, '%.1f MB' % (os.path.getsize(built) / 1e6)
    bad = [l for l in out.splitlines() if 'error' in l.lower() or 'failed' in l.lower()]
    return False, (bad[0][:90] if bad else 'build failed (see log)')


def show():
    print('%-20s %-7s %-7s %-9s %s' % ('map', 'tag', 'script', 'built', 'profiles'))
    for short, lvl in LEVELS:
        d = bytearray(open(scenario_path(lvl), 'rb').read())
        res = L.resource_path(H2EK, lvl)
        names = (L.names_in(bytearray(open(res, 'rb').read()), L.RES_NAMES, L.NES)
                 if os.path.isfile(res) else [])
        tag = 'YES' if all(n in names for n in L.CAMO_OBJECT_NAMES) \
                       and L.SPRINT_PROFILE in L.profile_names(d) else '-'
        h = mission_hsc(lvl)
        txt = open(h, encoding='latin-1').read() if os.path.isfile(h) else ''
        scr = 'current' if BEGIN in txt else ('legacy' if 'ab_camo_spawn' in txt else '-')
        built = os.path.join(MAPS_OUT, lvl + '.map')
        b = '%.0f MB' % (os.path.getsize(built) / 1e6) if os.path.exists(built) else '-'
        print('%-20s %-7s %-7s %-9s %s' % (lvl, tag, scr, b,
                                           ', '.join(L.profile_names(d)[:3])))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--maps', default='', help='comma list of short names (05a) or level dirs')
    ap.add_argument('--stage', default='tag,script,scripts,build',
                    help='tag,script,scripts,build (default all)')
    ap.add_argument('--show', action='store_true')
    ap.add_argument('--logdir', default=os.path.join(os.path.dirname(
        os.path.abspath(__file__)), 'out', 'h2logs'))
    a = ap.parse_args(argv)

    if a.show:
        return show()

    want = [s.strip() for s in a.stage.split(',') if s.strip()]
    sel = [s.strip() for s in a.maps.split(',') if s.strip()]
    levels = ([BY_SHORT.get(s, s) for s in sel] if sel else [l for _, l in LEVELS])
    os.makedirs(a.logdir, exist_ok=True)

    ok = fail = 0
    for lvl in levels:
        print('\n=== %s' % lvl)
        t0 = time.time()
        good = True
        for stage, fn in (('tag', apply_tag), ('script', install_stub)):
            if stage in want and good:
                good, msg = fn(lvl)
                print('  %-8s %-4s %s' % (stage, 'OK' if good else 'FAIL', msg))
        for stage, fn in (('scripts', rebuild_scripts), ('build', build_cache)):
            if stage in want and good:
                good, msg = fn(lvl, a.logdir)
                print('  %-8s %-4s %s' % (stage, 'OK' if good else 'FAIL', msg))
        print('  %.0fs' % (time.time() - t0))
        ok += good
        fail += not good

    print('\nDONE: %d ok, %d failed. Logs in %s' % (ok, fail, a.logdir))
    return 1 if fail else 0


if __name__ == '__main__':
    sys.exit(main() or 0)
