r"""Regenerate the Run Enhancer ability block in H2EK global_scripts.hsc, per player.

The effect table is lifted out of the CURRENT file rather than retyped, so the
in-game-picked fx_kind ids keep their meanings.
"""
import os
import re

HSC = r'F:\SteamLibrary\steamapps\common\H2EK\data\globals\global_scripts.hsc'
HEAD_MARK = ('; ---------------------------------------------------------------------------\n'
             '; RUN ENHANCER ABILITIES')

text = open(HSC, encoding='latin-1').read()
head = text[:text.index(HEAD_MARK)]

# Pull the (id, effect path) pairs out of the player0 effect table, so the fx_kind ids
# that were walked through in game keep their meanings across regenerations. Reads
# ab_fx0 (what this script writes) or, the first time, the older combined ab_regen_fx.
for start, end in (('(script static void ab_fx0', '(script static void ab_fx1'),
                   ('(script static void ab_regen_fx', '(if (> (player_count) 1)')):
    if start in text:
        body = text[text.index(start):]
        body = body[:body.index(end)] if end in body else body
        break
else:
    raise SystemExit('no effect table found in %s -- nothing to regenerate from' % HSC)
FX = re.findall(r'\(if \(= fx_kind (\d+)\) \(effect_new_on_object_marker\s*\n'
                r'\s*"([^"]+)" \(player0\) ""\)\)', body)
assert len(FX) >= 18, len(FX)


def fx_script(n):
    lines = ['(script static void ab_fx%d' % n]
    for i, (kind, path) in enumerate(FX):
        tail = ')' if i < len(FX) - 1 else '))'
        lines.append('\t(if (= fx_kind %s) (effect_new_on_object_marker' % kind)
        lines.append('\t\t"%s" (player%d) "")%s' % (path, n, tail))
    return '\n'.join(lines)


BLOCK = r'''; ---------------------------------------------------------------------------
; RUN ENHANCER ABILITIES (Halo 2 port of sprint_toolkit/sprint.hsc)  -- PER PLAYER
;
; Generated by sprint_toolkit/h2_genscript.py. Edit that, not this.
;
; PER-PLAYER INPUT. Halo 2 ships no unit_get_current_flashlight_state and every
; player_action_test_* verb is any-player, which is why this used to be ONE ability
; shared by both players. It is a dll limit, not a script one, and the
; `per-player-flashlight` patch in sprint_toolkit/h2_dll_patch.py lifts it:
; `unit_get_enterable_by_player <unit>` -- used zero times by any campaign script -- is
; rewritten to answer "THAT UNIT's flashlight is on". So it is passed (player0) for
; player 1 and (player1) for player 2, and both players read identically.
;
; THE EARLIER ATTEMPT READ THE WRONG SOURCE, and the difference matters. The first
; version (`p2-vision-trigger`) read the local action bitfield at [0x1815E40D0]+0xB8+4.
; That is LOCAL CONTROLLER STATE: in networked co-op a remote player's presses never
; reach the other machine's array at all, so slot 1 stayed zero and player 2 was
; permanently dead. Measured in game 2026-08-10. Halo 1 never had the problem because
; it reads the UNIT, and unit state replicates -- so Halo 2 now reads the unit too.
; The field is unit+0x278, a float, 1.0 = on, found in `player_flashlight_on`
; (+789160 -> +69C600), which walks the players and compares exactly that.
;
; WITHOUT THE DLL PATCH the verb answers whatever the stock predicate did, so both
; players simply never trigger. Nothing breaks; the abilities are just inert.
;
; TRIGGERING. Because this is a genuine engine-maintained STATE rather than a latched
; action bit, both players rising-edge detect on it exactly as H1 does with fp0/fp1 --
; and nothing needs player_action_test_reset to clear anything. Holding the button no
; longer re-fires when the cooldown expires.
;
; The flashlight itself still toggles for both players, as it does in H1, where the
; toggle IS the trigger.
;
; ability0/ability1: 0 none, 1 sprint, 2 overshield, 3 camo, 4 regeneration.
; Both default to 0, so a built map is vanilla until the Enhancer patches them.
; ---------------------------------------------------------------------------

; ---- tuning: durations/cooldowns in ticks (30/sec) -------------------------
(global short sprint_ticks 90)        ; 3.0s
(global short sprint_cooldown 45)
(global short os_ticks 150)           ; active window before the cooldown starts
(global short os_cooldown 45)
(global real  os_shield 3.0)
(global short camo_ticks 150)         ; total cloak
(global short camo_cooldown 45)
(global short camo_reapply 100)       ; ticks between re-applications (< the ~4s cap)
(global short medi_ticks 150)
(global short medi_cooldown 45)
(global real  medi_rate 0.5)          ; per-tick heal; the tuner computes it from medi_heal
; vit_max is the engine's absolute vitality scale: unit_get_health/_shield return a
; [0,1] fraction of it while unit_set_current_vitality takes absolute units. Halo 1
; measured 75; Halo 2 measured 70 (x1/x2/x3 overshield came out at 0.01425/0.0285/
; 0.04275, i.e. 1/70). Close enough to look interchangeable and wrong enough to drift,
; so the H1 value must NOT be assumed here. The patcher writes it either way.
(global real  vit_max 70.0)
(global short no_native_camo 0)       ; 1 = cancel engine camo every tick

; ---- per-player selected ability -------------------------------------------
(global short ability0 0)
(global short ability1 0)

; ---- per-player runtime state ----------------------------------------------
(global boolean sa0 false)            ; player 1: ability active
(global short   sl0 0)                ;           ticks left in the active window
(global short   sc0 0)                ;           cooldown ticks left
(global short   cn0 0)                ;           ticks until the next camo re-apply
(global boolean sa1 false)            ; player 2
(global short   sl1 0)
(global short   sc1 0)
(global short   cn1 0)
; Flashlight state last tick, per player -- the rising edge is what fires an ability.
; Same role as fp0/fp1 in H1's sprint.hsc.
(global boolean fp0 false)
(global boolean fp1 false)

; Forces the camo tag into the built map: a typed <object_definition> creates a real
; dependency where the plain string `drop` takes does not. Never called.
(script static void ab_dep
	(object_type_predict "objects\powerups\active_camouflage\active_camouflage"))

; Camo spawns a NAMED placement and sprint hands over a starting PROFILE; both resolve
; by name at compile time and both are per scenario, so these are stubs each level
; defines over (Bungie's own pattern). sprint_toolkit/h2_loosetag.py inserts ab_camo0/1
; and the ab_sprint profile into every scenario tag before the scripts compile, so no
; name is borrowed and h2_batch.py generates identical text on all 13 missions.
(script stub void ab_camo_spawn0
	(print "no camo placement on this level"))
(script stub void ab_camo_spawn1
	(print "no camo placement on this level"))
(script stub void ab_sprint_give0
	(print "no sprint profile on this level"))
(script stub void ab_sprint_give1
	(print "no sprint profile on this level"))

; Taking the sprint token back is objects_delete_by_definition, which is GLOBAL -- it
; has no unit argument, so it cannot disarm one player without disarming the other.
; It therefore only runs once NEITHER player is sprinting; if player 1's window ends
; while player 2 is still sprinting, player 1 keeps the token until player 2 stops too.
; That overlap is an engine limit, not a bug to chase: there is no per-unit remove verb.
(script static void ab_sprint_stop
	(if (not (or (and sa0 (= ability0 1)) (and sa1 (= ability1 1))))
		(objects_delete_by_definition "objects\weapons\melee\unarmed\unarmed")))

; ---- activation / deactivation, one pair per player -------------------------
; (HSC cannot take a unit by variable, so both players are written out.)

(script static void ability_start0
	(set sa0 true)
	(if (= ability0 1) (begin (set sl0 sprint_ticks) (ab_sprint_give0)))
	(if (= ability0 2) (begin (set sl0 os_ticks) (object_set_shield (player0) os_shield)))
	(if (= ability0 3) (begin (set sl0 camo_ticks) (set cn0 camo_reapply) (ab_camo_spawn0)))
	(if (= ability0 4) (set sl0 medi_ticks)))

(script static void ability_stop0
	(set sa0 false)
	(if (= ability0 1) (set sc0 sprint_cooldown))
	(if (= ability0 2) (set sc0 os_cooldown))
	(if (= ability0 3) (set sc0 camo_cooldown))
	(if (= ability0 4) (set sc0 medi_cooldown))
	(if (= ability0 1) (ab_sprint_stop)))

(script static void ability_start1
	(set sa1 true)
	(if (= ability1 1) (begin (set sl1 sprint_ticks) (ab_sprint_give1)))
	(if (= ability1 2) (begin (set sl1 os_ticks) (object_set_shield (player1) os_shield)))
	(if (= ability1 3) (begin (set sl1 camo_ticks) (set cn1 camo_reapply) (ab_camo_spawn1)))
	(if (= ability1 4) (set sl1 medi_ticks)))

(script static void ability_stop1
	(set sa1 false)
	(if (= ability1 1) (set sc1 sprint_cooldown))
	(if (= ability1 2) (set sc1 os_cooldown))
	(if (= ability1 3) (set sc1 camo_cooldown))
	(if (= ability1 4) (set sc1 medi_cooldown))
	(if (= ability1 1) (ab_sprint_stop)))

; ---- regeneration ------------------------------------------------------------
; unit_set_current_vitality takes ABSOLUTE units while the getters return [0,1], so
; every getter value is scaled by vit_max on the way back in. Body is clamped to
; vit_max; the shield is written back untouched.
(script static void medi_tick0
	(unit_set_current_vitality (player0)
		(min vit_max (+ (* (unit_get_health (player0)) vit_max) medi_rate))
		(* (unit_get_shield (player0)) vit_max)))

(script static void medi_tick1
	(unit_set_current_vitality (player1)
		(min vit_max (+ (* (unit_get_health (player1)) vit_max) medi_rate))
		(* (unit_get_shield (player1)) vit_max)))

; ---- feedback effects --------------------------------------------------------
; H2 shows no health bar, so the pulse is the only instrument regeneration has. Only
; SELF-CONTAINED effects work on a player: anything under impact\ or contact\ is
; material-driven, resolves its particles against the surface it hit, and silently
; draws nothing. The ids below were walked through in game; keep them stable.
(global short fx_kind 8)
(global short fx_every 45)
(global short fxp0 0)
(global short fxp1 0)

__FX0__

__FX1__

(script static void medi_pulse0
	(set fxp0 (- fxp0 1))
	(if (< fxp0 1) (begin (set fxp0 fx_every) (ab_fx0))))

(script static void medi_pulse1
	(set fxp1 (- fxp1 1))
	(if (< fxp1 1) (begin (set fxp1 fx_every) (ab_fx1))))

; ---- "ability ready" cue -----------------------------------------------------
; Fires on the tick that player's cooldown reaches zero. A burst reads far better than
; a single flash, so the cue arms a counter and the tick loop spends it. It reuses the
; ab_fx dispatcher by swapping fx_kind around the call rather than repeating a
; 19-entry table a third and fourth time.
(global short fx_ready 2)             ; elite shield recharge -- picked in game
(global short fx_ready_n 3)
(global short fx_ready_gap 10)
(global short rdy0 0)
(global short rdyt0 0)
(global short rdy1 0)
(global short rdyt1 0)
(global short fx_swap 0)

(script static void ab_ready0
	(if (> fx_ready 0)
		(begin
			(set fx_swap fx_kind)
			(set fx_kind fx_ready)
			(ab_fx0)
			(set fx_kind fx_swap))))

(script static void ab_ready1
	(if (> fx_ready 0)
		(begin
			(set fx_swap fx_kind)
			(set fx_kind fx_ready)
			(ab_fx1)
			(set fx_kind fx_swap))))

; ---- per-tick control --------------------------------------------------------
(script continuous ability_control
	; ---- player 1 ----
	(if (> sc0 0)
		(begin
			(set sc0 (- sc0 1))
			(if (= sc0 0) (begin (set rdy0 fx_ready_n) (set rdyt0 0)))))
	(if (> rdy0 0)
		(begin
			(set rdyt0 (- rdyt0 1))
			(if (< rdyt0 1)
				(begin
					(set rdy0 (- rdy0 1))
					(set rdyt0 fx_ready_gap)
					(ab_ready0)))))
	(if sa0
		(begin
			(set sl0 (- sl0 1))
			(if (= ability0 4) (begin (medi_tick0) (medi_pulse0)))
			; Camo duration is owned by the SCRIPT: the engine cuts the Arbiter's cloak
			; after ~4s whatever the pickup's Powerup Time says, so the pickup is kept
			; short and re-applied until the window runs out. That makes the patcher's
			; duration authoritative and Chief and the Arbiter behave the same.
			(if (= ability0 3)
				(begin
					(set cn0 (- cn0 1))
					(if (< cn0 1) (begin (set cn0 camo_reapply) (ab_camo_spawn0)))))
			(if (<= sl0 0) (ability_stop0)))
		; The hijacked verb reads THIS unit's flashlight, so the rising edge is the
		; press -- exactly as H1 does. See the header for why it is not an action test.
		(if (and (> ability0 0) (= sc0 0)
				 (unit_get_enterable_by_player (player0)) (not fp0))
			(ability_start0)))
	(set fp0 (unit_get_enterable_by_player (player0)))

	; ---- player 2 (only if present) ----
	(if (> (player_count) 1)
		(begin
			(if (> sc1 0)
				(begin
					(set sc1 (- sc1 1))
					(if (= sc1 0) (begin (set rdy1 fx_ready_n) (set rdyt1 0)))))
			(if (> rdy1 0)
				(begin
					(set rdyt1 (- rdyt1 1))
					(if (< rdyt1 1)
						(begin
							(set rdy1 (- rdy1 1))
							(set rdyt1 fx_ready_gap)
							(ab_ready1)))))
			(if sa1
				(begin
					(set sl1 (- sl1 1))
					(if (= ability1 4) (begin (medi_tick1) (medi_pulse1)))
					(if (= ability1 3)
						(begin
							(set cn1 (- cn1 1))
							(if (< cn1 1) (begin (set cn1 camo_reapply) (ab_camo_spawn1)))))
					(if (<= sl1 0) (ability_stop1)))
				; The SAME verb as player 1, just passed player 2's unit -- that is the
				; whole point of reading the unit rather than the local input array.
				(if (and (> ability1 0) (= sc1 0)
						 (unit_get_enterable_by_player (player1)) (not fp1))
					(ability_start1)))
			(set fp1 (unit_get_enterable_by_player (player1)))))

	(if (> no_native_camo 0) (cheat_active_camouflage false))
	; No player_action_test_reset here any more: nothing reads an action test, so there
	; is nothing to consume. The flashlight toggles for both players, as it does in H1.
	(sleep 1))
'''

BLOCK = BLOCK.replace('__FX0__', fx_script(0)).replace('__FX1__', fx_script(1))
out = head + BLOCK
open(HSC, 'w', encoding='latin-1', newline='\n').write(out)
print('wrote %s (%d effects x 2, %d bytes)' % (os.path.basename(HSC), len(FX), len(out)))
